app:
  image: datadoglt/base
  command: /bin/true
  volumes:
    - ".:/var/www"

web:
  build: docker/nginx
  volumes_from: [app]
  links:
   - php
  ports:
   - "80:80"

php:
  image: datadoglt/php:56
  volumes_from: [app]
  working_dir: /var/www
  links:
   - mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: vault

webtools:
  image: datadoglt/webtools
  volumes_from: [app]
  working_dir: /var/www
  environment:
    GULP_TASK: watch
